require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'log/**/*'
    - 'tmp/**/*'
    - '**/Gemfile'
    - 'vendor/**/*'

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/LineLength:
  Enabled: true

Lint/EmptyClass:
  Exclude:
    - 'app/models/application.rb'   # Empty class for CanCanCan

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/ClassLength:
  Max: 140
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 17

Naming/FileName:
  Exclude:
    - 'Capfile'

# TODO: app/controllers/application_controller.rb : @contest neeeds to be refactorized.
Naming/MemoizedInstanceVariableName:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: slashes

Security/YAMLLoad:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/StringMethods:
  Enabled: true

# TODO: Code in config/initializers/social_media_text.rb needs to be refactored
Style/DocumentDynamicEvalDefinition:
  Enabled: false
